// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var iapOfferConfig = IapOfferConfig.FromJson(jsonString);

namespace QuickType.IAPOffer
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class IapOfferConfig
    {
        [JsonProperty("android_id")]
        public string AndroidId { get; set; }

        [JsonProperty("ios_id")]
        public string IosId { get; set; }

        [JsonProperty("enable")]
        public bool Enable { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }
    }

    public partial class IapOfferConfig
    {
        public static IapOfferConfig FromJson(string json) => JsonConvert.DeserializeObject<IapOfferConfig>(json, QuickType.IAPOffer.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this IapOfferConfig self) => JsonConvert.SerializeObject(self, QuickType.IAPOffer.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
